### ISSUE TITLE
Can't open search.json.mozlz4 file, greyed out

### ISSUE THREAD

**Issue by nadesco** [soufianesakhi/firefox-search-engines-helper#16] opened 2020-10-21 05:45 UTC
Hi,
I've just tried to export my search engines to a json file using FSEH but couldn't open _search.json.mozlz4_ (or any other file) in the FF Profile because it was greyed out. What I did...

Clicked on _Export all search engines to a json file_ > Clicked on browse and navigated to the Profiles folder.

Because I couldn't select the file in question, I clicked on Options in the bottom left corner and changed the Format from _*.json.mozlz4_ to _All Files_. I was then able to select _search.json.mozlz4_ and click Open, but a notification popped up saying "Firefox Search Engines Helper Error".

I right-clicked Inspect Element > Console in the export window but there were no error messages.

Mac 10.14.6, Firefox 82.0
Search Engine Helper 3.1.0

Not sure if it's something I'm doing wrong or whether it's an issue, but that's what I get.

Thanks

**Comment by soufianesakhi** [comment] 2020-10-21 08:50
I was unable to reproduce on Windows, maybe it's relating to Mac?
I can't test on Mac right now but I will do when possible.

**Comment by nadesco** [comment] 2020-10-21 09:02
Ok, thanks.

**Comment by soufianesakhi** [comment] 2020-10-21 20:11
I was able to test with macOS Catalina (10.15), the export was successful (you may need to display hidden files to access the profile folder, and choose **all files** instead of **\*.json.mozlz4**).
I suspect a problem with the parsing of the json file.
If you want, you can send me your **search.json.mozlz4** file to investigate further to my email: soufiane.sakhi.js@gmail.com

**Comment by nadesco** [comment] 2020-10-22 00:37
I did try choosing All Files instead of *.json.mozlz4 but got a notification saying "Firefox Search Engines Helper Error” (see post above).
No problem to send you the search.json.mozlz4 file as you requested but the greying out is of all files, not just search.json.mozlz4, so I suspect it’s something to do with my mac rather than that one in particular.
Anyway, thanks for checking it out and getting back to me.

**Comment by soufianesakhi** [comment] 2020-10-31 17:37
I'm closing this issue. If you any update feel free to share.

**Closed as completed by soufianesakhi** 2020-10-31 17:37 UTC
